### ISSUE TITLE
Lay foundation for UI tests

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#128]
## User story
1. As a SD
2. I want / need to do research regarding testing UI-components in an automated way 
3. So that we test our functionalities properly and make sure to fulfill the requirements set by the customer

## Acceptance criteria
- [x] Do research on how to test UI-components in an automated way
- [x] Write a sample test case for UI
- [x] Lay the foundation that we can in the next sprint as a whole team directly start writing UI-tests
- [x] Make sure to summarize your findings in a way that other SDs who are not assigned to this issue know how testing UI-components works

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by codingwithelijah** [comment]
@domi1504: What is the current status regarding this issue? How can we proceed regarding issue #137 ?

**Comment by domi1504** [comment]
There is some substantial progress. I managed to get the UI-Tests running on both, my emulator and my physical smartphone.
After our talk with Markus last Friday I am also relieved, as he stated that local UI-Tests (not necessarily on the pipeline) are enough. That way, I want to set up the PR with first UI-Tests (which I also have written, but only very basic ones) tomorrow.
After that, I hope that as many devs as possible will be able to get them running on some device & will be able to write UI-Tests.
