### ISSUE TITLE
Write UI-tests to make sure we reach > 75 % test code coverage

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#137]
## User story
1. As a SD
2. I want / need meet the requirements set by the customer
3. So that we have a successful collaboration with happy customers in the end

## Further description
* Based on the foundation layed in #128, now focus on the creation of tests

## Acceptance criteria

- [ ] * Write tests to cover the UI-components of our app
- [ ] * Make sure to improve the overall test code coverage by a substantial amount of percentage points
- [x] Check for Android
- [ ] Check for iOS

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Interperle** [comment]
For iOS I'm waiting for Markus mail
