### ISSUE TITLE
Ensure known BLE devices are visually encoded when emitting a signal

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#142]
## User story
1. As a user 
2. I want / need to quickly access previously labeled BLE devices
3. So that I can faster access a desired feature for my preferred device

## Acceptance criteria
- [x] tag saved devices that are currently emitting a bluetooth signal with a flag that indicates a signal emitting [TBD IN TEAM MEETING]
- [x] only tag saved BLE devices once when user clicks on "Scan devices"
- [x] grey out BLE device name and disable button to signal strength for those BLE devices that are not emitting a signal

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Chippelius** [comment]
@Meisterlu @codingwithelijah we decided to combine this functionality with the foreground service that updates the GPS locations, since both of these things want to regularly know whether known devices are within range. Due to that, we will ignore the second acceptance criterium of only updating the indicator when the search button has been pressed. 

Secondly, we will ignore the third acceptance criterium, since it does not make sense to disable the strength button within the list. This is for one, becuase the user can simply select the device and then switch to the strength page via the flyout menu, achieving the same result, so the app-behavior would be inconsistent in what it allows. And for two, because when the user is reasonably within range according to the geolocation, he wants to switch to the strength page, **even if the device is currently still out of range**, in order to see when it does come into range.

**Comment by codingwithelijah** [comment]
@Chippelius and @Wandinad: Thank you guys for the update! Your comment makes sense from our side and is approved. Could you still please send a short screenrecording/screenshots showing how you implemented the solution?

**Comment by Chippelius** [comment]
The circle indicates whether the device is within range (gray = no, green = yes). Noticing that a device is within range takes at max as long as the interval set in the settings (usually less), noticing that it is out of range takes about twice this interval. 

![grafik](https://user-images.githubusercontent.com/30323292/175981957-ca533d7d-9da0-429e-97c4-c27e3178e279.png)
![grafik](https://user-images.githubusercontent.com/30323292/175981990-af791310-66fa-4538-9dd4-b75dd2b84366.png)
![grafik](https://user-images.githubusercontent.com/30323292/175982024-8d0fc5bd-743a-46b9-af2f-61e33782be79.png)
