### ISSUE TITLE
Minor UI-adjustments for detection view

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#143]
## User story
1. As a user
2. I want / need have self explanatory and intuitive icons used for features
3. So that I can quickly access a desired feature

## Acceptance criteria
- [ ] Delete "Scan"-button on the top right corner
- [ ] Next to each saved device, place two buttons that navigate to the signal strength or geolocation feature respectively:
- [ ] <img width="160" alt="image" src="https://user-images.githubusercontent.com/74047429/173549655-97630ba6-feb1-4f4c-a8d7-95ed9c6d2b04.png">

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jannikbmc** [comment]
The scan button is removed and the itempage and itemdetailpage show the desired icons. Sorry for the late reply, i've been sick.

![photo_2022-06-29_20-20-04](https://user-images.githubusercontent.com/52490096/176508167-182b4168-e458-41f1-a8d8-5d63c0989cdc.jpg)
![photo_2022-06-29_20-20-02](https://user-images.githubusercontent.com/52490096/176508170-01525b43-d229-47d6-bccb-944d7494f6b0.jpg)
