### ISSUE TITLE
Ensure to allow user to switch to OS specific map via buttons labeled with the name of the navigation system

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#194]
## User story
1. As a user
2. I want / need be able to switch to the map app of my device
3. So that app-overarching features like "apple carplay" are supported

## Acceptance criteria
- [x] integrate button to allow user to switch to map app
- [x] Intergrate name of the map app within button
- [x] Ensure that location of the device and smartphone is transferred into map app 
- [x] Check if its possible to integrate bigger, more intuitive button 

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by NicoStellwag** [comment]
@Chippelius could you please post the exact error message you get?
Thanks in advance!

**Comment by Chippelius** [comment]
![Screenshot_20220628-123825](https://user-images.githubusercontent.com/30323292/176917785-fd309ee6-186d-460c-a2c8-ef75efcee6f4.jpg)

**Comment by jannikbmc** [comment]
We are waiting for Marib to test it on iOS, but yes.
![photo_2022-07-04_13-52-49](https://user-images.githubusercontent.com/52490096/177149623-30b3c533-b21b-4fbc-9a6d-c337cf74d4bd.jpg)
