### ISSUE TITLE
Collect quick wins to Start implementing design as provided by POs in FIGMA

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#214]
## User story
1. As a user
2. I want / need to use an app that is easy to use and visually pleasing
3. So that my tendency to frequently use the app increases

## Further description
Please find under acceptance criteria the figma draft both POs created. This serves as a first idea which needs to be checked regarding feasibility in Xamarin. Please work closely with POs, especially during this design phase, to coordinate how PO suggestions might be implemented. 

## Acceptance criteria
- [x] Have a look at the draft in FIGMA (https://www.figma.com/file/YskCZiMmKxNVSV62LhZNGo/Untitled?node-id=0%3A1) and gather ideas what UI improvements could be quick wins
- [x] Schedule meeting with POs to discuss the quick wins we can implement
- [x] Start implementing the UI ideas and lay foundation for further changes

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Meisterlu** [comment]
Icons:
- https://img.icons8.com/ios-filled/344/settings.png
- https://img.icons8.com/ios-glyphs/344/wifi--v1.png
- https://img.icons8.com/ios/344/wifi--v1.png
- https://img.icons8.com/ios/344/marker--v1.png
- https://img.icons8.com/ios/344/home--v1.png

All icons should be referenced with: [Home](https://icons8.com/icon/73/home) icon by [Icons8](https://icons8.com/)

**Comment by Chippelius** [comment]
@Meisterlu @codingwithelijah the acceptance criteria state that info regarding colors and fonts can be found in figma, but using your figma link, I can only see the design as a whole, no additional info is provided

**Comment by Meisterlu** [comment]
@Chippelius yes you can find the information within Figma. When you click on a certain text, lets say "Welcome" in the beginning, you see on the right options, where one says "inspect". In there you get details regarding fonts and colors. We can also have a look on it together later after the workshop if you want.

**Comment by Chippelius** [comment]
I'm afraid that's not possible in spectator mode. 
Please provide the primary, secondary, accent, etc. colors as rgb/hex codes here. 
This also makes for easier referencing, since the figma site is very slow to load, so having it here in GitHub would be beneficial anyways.

**Comment by NicoStellwag** [comment]
@Chippelius @jannikbmc @Interperle @Meisterlu @codingwithelijah
Please vote for a timeslot for the ui quickwins meeting until saturday evening:
https://doodle.com/meeting/participate/id/dJZjnJvd

@Meisterlu @codingwithelijah 
This workitem was just about scheduling the meeting and informing the others about the outcome, right?
If otherwise, could you please update the acceptance criteria?

**Comment by Chippelius** [comment]
![grafik](https://user-images.githubusercontent.com/30323292/177010827-a732e207-16c5-487e-ba02-f0097479ddeb.png)

TabBar navigation is really easy to implement, I just had to turn the "FlyoutItem" elements into "Tab" elements and surround them with a "TabBar" element (in AppShell.xaml): https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/tabs 
I would suggest leaving the TabBar at the bottom, but with a bit of trickery it should be possible to have it at the top: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/tabs#bottom-and-top-tabs 
It should even be fairly straitforward to make the TabBar disappear on the AboutPage, but visible on any other page: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/tabs#tabbar-and-tab-visibility

**Comment by Meisterlu** [comment]
@NicoStellwag yes I will do so tomorrow and Update the ACs 
@same applies for colors and fonts I am currently not at home @Chippelius but if it's needed now and really urgent I could gather it now

**Comment by Chippelius** [comment]
![grafik](https://user-images.githubusercontent.com/30323292/177020439-a2738de8-2e12-4962-8823-71616d879f9a.png)

Status update: Gradient backgrounds work, buttons with image and text are, for WHATEVER REASON (*cough* Microsoft *cough*), pretty tricky/hacky to implement, but possible. 
And please don't ask about making the status bar at the top transparent... (I tried, it's possible, but introduces so many problems that I highly discourage it). Just pick an opaque color and be happy.

**Comment by Chippelius** [comment]
And before I forget: 
This will probably be helpful for adding the devices-overlay to every page: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/control-template#substitute-content-into-a-contentpresenter 
And the swipe-up mechanic will probably be possible with a gesture recogniser (bit with swipe instead of tap as the trigger), but I haven't yet looked into it

**Comment by NicoStellwag** [comment]
The meeting is set for tuesday, 19:00 to 20:00.

**Comment by Meisterlu** [comment]
Alright, so hex code of the colours are: 
Background colour welcome page: linear gradient, top right #0C488E to left bottom #051B2E
Background colour signal strength and geolocation solution: linear gradient, top right #0C488E to left bottom #C0D7EB
Secondary colour: #DAE5F1
Third colour/accent colour: #7797B8
Fourth colour/darker accent colour: #0B407B

@Chippelius let me know if you need anything more :)

**Comment by Meisterlu** [comment]
@NicoStellwag ACs are also updated :)
