### ISSUE TITLE
Calculate route to lost BLE device for different transportation options

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#215]
## User story
1. As a user
2. I want / need to see how much time it takes me to navigate to my lost BLE device inside the geolocation feature for different transportation options
3. So that I can select a solution that best reflects my preferences

## Acceptance criteria
- [ ] Allow user to select different transportation options for the navigation inside the geolocation feature
- Transportation options: 
- [ ] by car
- [ ] by foot
- [ ] by public transportation
- [ ] by bike
- [ ] use the visualization for the different transporation options provided by the OS-specific map 

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release
