### ISSUE TITLE
Ensure smartphone receives emitting signal when geolocation destination is reached

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#227]
## User story
1. As a user
2. I want / need be able to switch from the geolocation feature to the signal strength feature
3. So that the app guides me straight to the device

## Acceptance criteria
- [x] Ensure fluent transition between geolocation and signal strenght feature
- [x] When user remains in the geolocation map, a note is displayed as soon as emitting signal is received in the app. Note prompts user to switch directly to the signal strength feature
- [x] Prepare screen recording where you first search for the device in the geolocation feature and are guided via the google maps route, when destination is reached, switch back to the app. Open the signal strength feature and navigate to the lost device by making use of the signal strength feature

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by NicoStellwag** [comment]
@domi1504 important update:
new branch based on refactored codebase: 227-reachable-notification-rebased

**Comment by codingwithelijah** [comment]
@domi1504: Looks great! Could you provide details regarding the screenrecording here, please? 
Eg.: Was the lost BLE device placed outside in the grass without any possible obstacles (walls, other devices, ...) in the surrounding? Would you have been able to find the lost device by solely relying on geolocation and strength search without knowing in advanced where you placed the lost device - be honest! :D 

Thanks for your update!

**Comment by domi1504** [comment]
Since my powerbank always automatically turns off with the arduino connected to it, i had to place it where i had a power supply. It was placed in an entry of a house. No direct obstacles in front of it, but obviously therefor surrounded by walls.

To your question whether I would have found it, I must admit I don't know for sure. My intuition says yes, everything worked as expected. But there is always a bias when you already know where you have to search. I think the only way to really find out would be to have someone else hide the BLE-Device from you, so you REALLY have to search for it. xD
