### ISSUE TITLE
Ensure correct handling when user does not provide all rights 

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#231]
## User story
1. As a user
2. I want / need to be informed of basic rights (usage of DB-writing, GPS and Bluetooth) the app is based on
3. So that I know transparently about the reasons for app misbehavior

## Acceptance criteria
- [x] Ensure all rights are provided when user enters the app for the first time (writing, GPS and Bluetooth) by showing a popup and prompting the user to accept rights
- [x] Ensure popup re-appears when user changes the rights settings and not all necessary rights are provided
- [x] If the user does not agree on all necessary rights, a note will appear: "Attention, necessary rights are not given. Thus, the basic functionalities of this app are affected and cannot be used."
- [x] Make sure it works on iOS

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

Vieleicht macht da ein Decision-Tree Sinn:
