### ISSUE TITLE
Create a documentation about the guidance part when user clicks on "?"

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#236]
## User story
1. As a user
2. I want / need be able to have a proper guidance in the app
3. So that I am able to educate myself whenever I do not understand the way the app works

## Acceptance criteria
- [x] Have brainstorm session where you gather ideas on possible guidance issues to tackle within this section
- [x] make sure to explain the features and handlings of the app explictly so our target group (rather older people) are able to understand it
- [x] Create a documentation where you structure your ideas and findings well, ready to be implemented easily in the next sprint

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by codingwithelijah** [comment]
- https://docs.microsoft.com/en-us/xamarin/community-toolkit/views/popup
- Presentation from Markus

**Comment by codingwithelijah** [comment]
# Results from Brainstorming Session:
> General Note: We decided to display different text when clicking on the "?"-button, based on the page the user currently is. This will be implemented in the next sprint by displaying popups. 

## Welcome-Screen: 
Welcome to our "Find your BLE devices"-App. By clicking on the question mark, you will receive individual help on the different pages of our app. Our two core functionalities consist of "Strength Search" and "Map Search".
"Strength Search" measures the distance to your lost device based on the emitting Bluetooth signal. "Map Search" shows the last known GPS coordinate of your lost device. 
The tab bar at the bottom of this page allows you to directly navigate to your desired function. With the button above, you can select your desired device. 

## Saved Devices-Sreen: 
By clicking on "Scan for available devices" all devices in your surrounding that are currently emitting a Bluetooth signal are displayed. You can permanently store a device on your app by clicking on the device and by assigning it an individual name. Click on a device in the "Saved Devices" section to select a device. The settings symbol next to the device allows you to display device specific details. 

## Edit saved devices-Screen: 
On this screen you can rename your device, find additional information and delete the device from the "Saved Devices" section of the previous page. 

## Strength Search: 
"Strength Search" measures the distance to your lost device based on the emitting Bluetooth signal. By moving around, the blue circle radius changes. If you move away from your device, the circle radius will increase. If you approach your device, the circle radius will decrease. 

## Map Search: 
"Map Search" shows the last known GPS coordinate of your lost device. Please note that the displayed GPS coordinate is the latest tracked location of your smartphone while having a connection to your device. The "Open in maps"-button will forward you to your local map app to start a navigation. After you have reached your destination, you can switch to the "Strength Search" within the app to track your device in your near surrounding.
