### ISSUE TITLE
[DUE: SAT] Go through app to ensure consistent wording

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#252]
## User story
1. As a user
2. I want / need to use an app with consistent wording
3. So that I am helped to become familiar with the digital landscape of the product

## Further description: 
We want to make sure that we are consistent in wording. Consistence also covers minor wording improvements that sound more natural, spelling mistakes, improved sentence structure and more meaningful words. 

## Acceptance criteria
- [x] Go through the app on iOS and identify inconsistencies in wording
- [x] Go through the app on Android and identify inconsistencies in wording
- [x] Provide a summary of identified inconsistencies in the comments of this issue and already suggest an improvement. 

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by codingwithelijah** [comment]
This is the structure to use for the result presentation of this issue: 


|Location of inconsistency  |Description of inconsistency  | On iOS? | On Android? | Suggested improvement
|--|--|--|--|--|
|Placeholder  |Placeholder  |[Y or N]  | [Y or N] |Placeholder  |
|Placeholder  |Placeholder  |[Y or N]  | [Y or N] |Placeholder  |
|Placeholder  |Placeholder  |[Y or N]  | [Y or N] |Placeholder  |
|Placeholder  |Placeholder  |[Y or N]  | [Y or N] |Placeholder  |
|Placeholder  |Placeholder  |[Y or N]  | [Y or N] |Placeholder  |
|Placeholder  |Placeholder  |[Y or N]  | [Y or N] |Placeholder  |
|Placeholder  |Placeholder  |[Y or N]  | [Y or N] |Placeholder  |

**Comment by codingwithelijah** [comment]
@Interperle and @domi1504: Please bear in mind that you have to do this issue after the merge tomorrow evening and before our next meeting on Saturday.

**Comment by Interperle** [comment]
|Location of inconsistency  |Description of inconsistency  | On iOS? | On Android? | Suggested improvement
|--|--|--|--|--|
| Title of Strength Search/Map Search page and Label in Bottom Menu  | The titles on the pages doesn't contain a blank/space and the Labels in the bottom Menu does (e.g. 'StrengthSearch' vs 'Strength Search'   | Y  | [Y or N] | Use the wording without Blank  |

**Comment by domi1504** [comment]
Not really a wording issue, but how about disabling landscape orientation?

**Comment by domi1504** [comment]
|Location of inconsistency  |Description of inconsistency  | On iOS? | On Android? | Suggested improvement
|--|--|--|--|--|
| Select device button | If no device selected: "Click **here** to select a device", else: "Click to select a different device" | [Y or N]  | Y | Change text to "Click to select a device" |

**Comment by codingwithelijah** [comment]
Decisions made in team meeting: 
1. Strength Search --> Blank between both words, for both the heading and the appearing popup when signal is received.
3. Name the "AboutPage" also in the backend "HomePage" --> No change here! 
4. Disable landscape mode for both Android and iOS
5. "Click to select a different device"
