### ISSUE TITLE
Agree on design pattern

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#68]
## User story
1. As a Developer
2. I want / need agree with the whole Dev-Team on a design pattern (e.g. MVVM) as proposed by IP
3. So that we can change the GUI later easily without breaking dependencies between the view and the logic 

## Acceptance criteria

- [x] agreed on design pattern 
- [x] agreed on interfaces from View to Model
- [x] regular update to POs via comments

**Comment by codingwithelijah** [comment]
@jannikbmc: See Discord Developer Channel for a video. Ask @Chippelius, @domi1504, @Interperle, @Wandinad if you have questions. They attended the meeting. 
If still something is unclear, you can directly reach out to Sebastian and Markus. Please add the whole team then in the CC. 
Thanks! :)

**Comment by jannikbmc** [comment]
@Meisterlu @codingwithelijah As you might have seen in the developers channel, the opinion on this is quite clear. We do not want to seperate the Views in another project and keep it as it is.
