### ISSUE TITLE
Improved Welcome screen

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#69]
## User story
1. As a user 
2. I want / need to have a page entitled "Welcome to our app" with a menu when I enter the app
3. So that I know what the app does and that I like to use the app

## Acceptance criteria
- [x] Replace logo of Xamarin with our own logo
- [x] Adjust the text provided on the welcome screen: Cut developer text and welcome user instead with a short message what the app does (see vision/mission for information)
- [x] Replace "Learn More"-Button with two buttons that navigate to our main features --> singnal strength and geolocation
- [x] Replace icons in the menu for our features with the following icons: 
- [x] <img width="150" alt="image" src="https://user-images.githubusercontent.com/74047429/173546265-8a444070-bc4c-4e17-a992-914178ba4f38.png">

## Definition of Done
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main
