### ISSUE TITLE
Extract a human readable name of each device in my surrounding

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#73]
## User story
1. As a user 
2. I want / need to have the name of the surrounding BLE devices displayed
3. So that I can identify my preferred device and then start a desired action with this device

## Acceptance criteria
- [x] Show name of the surrounding BLE device
- [x] No need to edit name
- [x] Similiar to name in the bluetooth settings in my smartphone

**Comment by NicoStellwag** [comment]
It seemed like devices not showing a display name are not meant to be connected to (all relevant devices like smartwatches, airpods, fitness trackers, ... send a name).
That's why we agreed on simply not displaying them in our app.

**Comment by Meisterlu** [comment]
@NicoStellwag makes sense. Sounds good, thanks for the update.

**Comment by Chippelius** [comment]
@domi1504 @jannikbmc @NicoStellwag I need the results of this issue in order to work on issue #80. Now there are two options: 

1. I can pull the changes directly from the branch of this issue. When I'm done, I will create a pull request into dev containing both, my changes and yours. In order to avoid merge conflicts it is important that you do not create a pull-request of your own in this case! (Pull-requests are what is listed in the release notes of the sprint release. I don't know how much you care about reading your name there, which is why I'm asking beforehand.) 
2. I can pull the changes from the dev branch after you created a pull-request that has been merged successfully. This would require you to ask the release manager (which is Marib for this sprint) to review and merge your pull-request before tomorrow afternoon, so I still have time to work on my own issue before the pull-request deadline. 

Which one would you prefer? (If your changes are not merged into dev by tomorrow, 4 pm, and you did not answer here, I'm assuming you want to go with option 1.)

**Comment by NicoStellwag** [comment]
@Chippelius We might have a little problem.
We had to do some changes to the database api and didn't rewrite the unit tests yet.
So some of them should fail (and therefore a PR should not work).

We still have some work left anyway, so I would propose you pull our changes directly from the bluetooth-work branch and work on your issue. Afterwards we merge your branch back into ours, fix the tests, and add our last feature.
Would that work for you?

**Comment by Chippelius** [comment]
@NicoStellwag after fighting with everything (git, VisualStudio, Xamarin, and Android) for far too long, I finally merged the navigate-to-signal-strength changes into a branch based on your bluetooth-work and created a Pull-Request assigned to you. 

It should work, at least it does run on my device, but I can't say for sure, because since the list of available devices is being filtered, I can't see any of my bluetooth devices in the app anymore (I'm talking about devices that do show up in the bluetooth settings with a name, but, as a reminder, they did not have a name in the app during my showcase in the last team meeting, so apparently they are now being filtered out for not having one.). 
We probably should look into that.
