### ISSUE TITLE
Implement discussed software hierarchy and create overview of components

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#93]
## User story
1. As a user
2. I want / need to be able to navigate to the desired feature from different entry points
3. So that different user behaviors are covered by our app. 

## Acceptance criteria
- [x] Create overview of all different views and how they are connected 
- [x] Also create an overview of the software hierarchy discussed in the meeting on Monday evening (June 6, 2022) --> [@Chippelius knows more about it]
- [x] Make sure to keep the functionality and adapt to the agreed design pattern

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Chippelius** [comment]
![Bildschirmfoto am 2022-06-15 um 01 42 20](https://user-images.githubusercontent.com/30323292/173707227-73f486ce-d58e-4ef4-be6a-820e2d34c9a3.png)
T

**Comment by codingwithelijah** [comment]
@Interperle, @jannikbmc, @NicoStellwag and @Wandinad: Please check it and reach out to Leo and Jannick if you disagree with some points.
